id: DAF977158
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:18:09+00:00'
last_modified: '2022-05-26T11:40:23.306512+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c9b5:
      image_group_id: I1PD95872
      title: འཇིག་རྟེན་ལས་འདས་པའི་ཡན་ལག་བདུན་པའི་ཆོ་ག།
      total_pages: 1953
      order: 27
      base_file: c9b5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
