id: cf8bee4c76d5422fb3376ef626ead10d
initial_creation_type: ocr
source_metadata:
  volumes:
    61a61e2778df403ab78f922a14fe0a81:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: འཇིག་རྟེན་ལས་འདས་པའི་ཡན་ལག་བདུན་པའི་ཆོ་ག།
      total_pages: 1953
      volume_number: 27
